[package]
name = "di_command"
version = "0.1.0"
authors = ["ippee <ippee.music@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "3.0.1"
